{% set version = "0.6.14" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rtables
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rtables_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rtables/rtables_{{ version }}.tar.gz
  sha256: 47a5b56433594f76c3e3f2d027af162ceae789db6c60bd3344f051204ed8ac9c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.5
    - r-htmltools >=0.5.4
    - r-magrittr >=1.5
    - r-stringi >=1.6
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.5
    - r-htmltools >=0.5.4
    - r-magrittr >=1.5
    - r-stringi >=1.6

test:
  commands:
    - $R -e "library('rtables')"           # [not win]
    - "\"%R%\" -e \"library('rtables')\""  # [win]

about:
  home: https://github.com/insightsengineering/rtables, https://insightsengineering.github.io/rtables/
  license: Apache-2.0
  summary: Reporting tables often have structure that goes beyond simple rectangular data. The 'rtables' package provides a framework for declaring complex multi-level tabulations and then applying them to data. This framework models both tabulation and the resulting tables as hierarchical, tree-like objects which support
    sibling sub-tables, arbitrary splitting or grouping of data in row and column dimensions, cells containing multiple values, and the concept of contextual summary computations. A convenient pipe-able interface is provided for declaring table layouts and the corresponding computations, and then applying them to data.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
