{% set version = "0.6.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rtables
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rtables_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rtables/rtables_{{ version }}.tar.gz
  sha256: 4717298dabe4101c8c05a4dda335be08b13c5128a698f734236b31fdc7b61c74

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.5
    - r-htmltools >=0.5.4
    - r-magrittr >=1.5
    - r-stringi >=1.6
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.5
    - r-htmltools >=0.5.4
    - r-magrittr >=1.5
    - r-stringi >=1.6

test:
  commands:
    - $R -e "library('rtables')"           # [not win]
    - "\"%R%\" -e \"library('rtables')\""  # [win]

about:
  home: https://github.com/insightsengineering/rtables, https://insightsengineering.github.io/rtables/
  license: Apache-2.0
  summary: Reporting tables often have structure that goes beyond simple rectangular data. The 'rtables' package provides a framework for declaring complex multi-level tabulations and then applying them to data. This framework models both tabulation and the resulting tables as hierarchical, tree-like objects which support
    sibling sub-tables, arbitrary splitting or grouping of data in row and column dimensions, cells containing multiple values, and the concept of contextual summary computations. A convenient pipe-able interface is provided for declaring table layouts and the corresponding computations, and then applying them to data.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
